# Generated by Django 3.0.1 on 2021-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('cd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cd_name', models.CharField(max_length=100)),
                ('cd_artist', models.CharField(max_length=100)),
                ('cd_language', models.CharField(max_length=30)),
            ],
        ),
    ]
