# Generated by Django 3.0.1 on 2021-02-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_cds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cd',
            name='cd_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
