# Generated by Django 3.0.1 on 2021-02-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreserve',
            name='days_for_expiry',
            field=models.IntegerField(default=5),
        ),
    ]
